# Generated by Django 6.0.3 on 2026-03-26 11:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_event'),
        ('tasks', '0004_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['project', 'created_at'], name='projects_ev_project_5118a6_idx'),
        ),
    ]
