# Generated by Django 6.0.3 on 2026-04-16 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_event_projects_ev_project_5118a6_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
    ]
